apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: react-frontend
build:
  artifacts:
    - image: frontend-app
      context: .
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - ./configuration/deployment.yaml

portForward:
  - resourceType: service
    resourceName: frontend-service
    port: 80
    localPort: 8082